# Generated by Django 3.2.7 on 2021-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211014_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
